// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/metricsherlock/metricviolations/v1/metric_violation_fact.proto

package metricviolationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViolationType int32

const (
	ViolationType_VIOLATION_TYPE_UNSPECIFIED        ViolationType = 0
	ViolationType_VIOLATION_TYPE_METRIC_NAME_LENGTH ViolationType = 1
	ViolationType_VIOLATION_TYPE_LABEL_NAME_LENGTH  ViolationType = 2
	ViolationType_VIOLATION_TYPE_LABEL_VALUE_LENGTH ViolationType = 3
	ViolationType_VIOLATION_TYPE_CARDINALITY        ViolationType = 4
	ViolationType_VIOLATION_TYPE_HISTOGRAM_BUCKETS  ViolationType = 5
	ViolationType_VIOLATION_TYPE_RESPONSE_WEIGHT    ViolationType = 6
)

// Enum value maps for ViolationType.
var (
	ViolationType_name = map[int32]string{
		0: "VIOLATION_TYPE_UNSPECIFIED",
		1: "VIOLATION_TYPE_METRIC_NAME_LENGTH",
		2: "VIOLATION_TYPE_LABEL_NAME_LENGTH",
		3: "VIOLATION_TYPE_LABEL_VALUE_LENGTH",
		4: "VIOLATION_TYPE_CARDINALITY",
		5: "VIOLATION_TYPE_HISTOGRAM_BUCKETS",
		6: "VIOLATION_TYPE_RESPONSE_WEIGHT",
	}
	ViolationType_value = map[string]int32{
		"VIOLATION_TYPE_UNSPECIFIED":        0,
		"VIOLATION_TYPE_METRIC_NAME_LENGTH": 1,
		"VIOLATION_TYPE_LABEL_NAME_LENGTH":  2,
		"VIOLATION_TYPE_LABEL_VALUE_LENGTH": 3,
		"VIOLATION_TYPE_CARDINALITY":        4,
		"VIOLATION_TYPE_HISTOGRAM_BUCKETS":  5,
		"VIOLATION_TYPE_RESPONSE_WEIGHT":    6,
	}
)

func (x ViolationType) Enum() *ViolationType {
	p := new(ViolationType)
	*p = x
	return p
}

func (x ViolationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViolationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_enumTypes[0].Descriptor()
}

func (ViolationType) Type() protoreflect.EnumType {
	return &file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_enumTypes[0]
}

func (x ViolationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViolationType.Descriptor instead.
func (ViolationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescGZIP(), []int{0}
}

type ServiceViolationFact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup   string                 `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Cluster       string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	TeamName      string                 `protobuf:"bytes,4,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	ViolationType ViolationType          `protobuf:"varint,5,opt,name=violation_type,json=violationType,proto3,enum=metricsherlock.metricviolations.v1.ViolationType" json:"violation_type,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	CurrentValue  int64                  `protobuf:"varint,7,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Violated      bool                   `protobuf:"varint,8,opt,name=violated,proto3" json:"violated,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceViolationFact) Reset() {
	*x = ServiceViolationFact{}
	mi := &file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceViolationFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceViolationFact) ProtoMessage() {}

func (x *ServiceViolationFact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceViolationFact.ProtoReflect.Descriptor instead.
func (*ServiceViolationFact) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceViolationFact) GetTargetGroup() string {
	if x != nil {
		return x.TargetGroup
	}
	return ""
}

func (x *ServiceViolationFact) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *ServiceViolationFact) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ServiceViolationFact) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *ServiceViolationFact) GetViolationType() ViolationType {
	if x != nil {
		return x.ViolationType
	}
	return ViolationType_VIOLATION_TYPE_UNSPECIFIED
}

func (x *ServiceViolationFact) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ServiceViolationFact) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *ServiceViolationFact) GetViolated() bool {
	if x != nil {
		return x.Violated
	}
	return false
}

func (x *ServiceViolationFact) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto protoreflect.FileDescriptor

const file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDesc = "" +
	"\n" +
	"Dproto/metricsherlock/metricviolations/v1/metric_violation_fact.proto\x12\"metricsherlock.metricviolations.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xee\x02\n" +
	"\x14ServiceViolationFact\x12!\n" +
	"\ftarget_group\x18\x01 \x01(\tR\vtargetGroup\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12\x1b\n" +
	"\tteam_name\x18\x04 \x01(\tR\bteamName\x12X\n" +
	"\x0eviolation_type\x18\x05 \x01(\x0e21.metricsherlock.metricviolations.v1.ViolationTypeR\rviolationType\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12#\n" +
	"\rcurrent_value\x18\a \x01(\x03R\fcurrentValue\x12\x1a\n" +
	"\bviolated\x18\b \x01(\bR\bviolated\x129\n" +
	"\n" +
	"checked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt*\x8d\x02\n" +
	"\rViolationType\x12\x1e\n" +
	"\x1aVIOLATION_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!VIOLATION_TYPE_METRIC_NAME_LENGTH\x10\x01\x12$\n" +
	" VIOLATION_TYPE_LABEL_NAME_LENGTH\x10\x02\x12%\n" +
	"!VIOLATION_TYPE_LABEL_VALUE_LENGTH\x10\x03\x12\x1e\n" +
	"\x1aVIOLATION_TYPE_CARDINALITY\x10\x04\x12$\n" +
	" VIOLATION_TYPE_HISTOGRAM_BUCKETS\x10\x05\x12\"\n" +
	"\x1eVIOLATION_TYPE_RESPONSE_WEIGHT\x10\x06BkZigit.server.lan/maksim/metric-sherlock-diploma/proto/metricsherlock/metricviolations/v1;metricviolationsv1b\x06proto3"

var (
	file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescOnce sync.Once
	file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescData []byte
)

func file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescGZIP() []byte {
	file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescOnce.Do(func() {
		file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDesc), len(file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDesc)))
	})
	return file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDescData
}

var file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_goTypes = []any{
	(ViolationType)(0),            // 0: metricsherlock.metricviolations.v1.ViolationType
	(*ServiceViolationFact)(nil),  // 1: metricsherlock.metricviolations.v1.ServiceViolationFact
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_depIdxs = []int32{
	0, // 0: metricsherlock.metricviolations.v1.ServiceViolationFact.violation_type:type_name -> metricsherlock.metricviolations.v1.ViolationType
	2, // 1: metricsherlock.metricviolations.v1.ServiceViolationFact.checked_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_init() }
func file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_init() {
	if File_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDesc), len(file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_goTypes,
		DependencyIndexes: file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_depIdxs,
		EnumInfos:         file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_enumTypes,
		MessageInfos:      file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_msgTypes,
	}.Build()
	File_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto = out.File
	file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_goTypes = nil
	file_proto_metricsherlock_metricviolations_v1_metric_violation_fact_proto_depIdxs = nil
}
