events {}

http {
  # DNS Docker
  resolver 127.0.0.11 valid=10s ipv6=off;

  # upstream с динамическим резолвом
  upstream metric_sherlock {
    zone metric_sherlock 64k;
    server metric-sherlock:7002 resolve;
  }

  upstream metric_sherlock_ui {
      zone metric_sherlock_ui 64k;
      server metric-sherlock-ui:80 resolve;
    }

  upstream kafbat_ui {
    zone kafbat_ui 64k;
    server kafbat-ui:8080 resolve;
  }

  server {
    listen 80;
    absolute_redirect off;

    location /api/ {
      proxy_pass http://metric_sherlock;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # чтобы не держал мёртвые соединения
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }

    location = /kafka-ui {
      return 302 /kafka-ui/;
    }

    location /kafka-ui/ {
      limit_except GET {
        deny all;
      }

      proxy_pass http://kafbat_ui;

      proxy_http_version 1.1;

      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;

      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }

    location / {
      proxy_pass http://metric_sherlock_ui;

      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # чтобы не держал мёртвые соединения
      proxy_connect_timeout 2s;
      proxy_read_timeout 10s;
    }
  }
}
