// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.0
// source: proto/metricsherlock/targetgroups/v1/target_groups.proto

package targetgroupsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetGroupsService_ListTargetGroups_FullMethodName = "/metricsherlock.targetgroups.v1.TargetGroupsService/ListTargetGroups"
	TargetGroupsService_GetTargetGroup_FullMethodName   = "/metricsherlock.targetgroups.v1.TargetGroupsService/GetTargetGroup"
)

// TargetGroupsServiceClient is the client API for TargetGroupsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TargetGroupsServiceClient interface {
	ListTargetGroups(ctx context.Context, in *ListTargetGroupsRequest, opts ...grpc.CallOption) (*ListTargetGroupsResponse, error)
	GetTargetGroup(ctx context.Context, in *GetTargetGroupRequest, opts ...grpc.CallOption) (*GetTargetGroupResponse, error)
}

type targetGroupsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetGroupsServiceClient(cc grpc.ClientConnInterface) TargetGroupsServiceClient {
	return &targetGroupsServiceClient{cc}
}

func (c *targetGroupsServiceClient) ListTargetGroups(ctx context.Context, in *ListTargetGroupsRequest, opts ...grpc.CallOption) (*ListTargetGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTargetGroupsResponse)
	err := c.cc.Invoke(ctx, TargetGroupsService_ListTargetGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *targetGroupsServiceClient) GetTargetGroup(ctx context.Context, in *GetTargetGroupRequest, opts ...grpc.CallOption) (*GetTargetGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTargetGroupResponse)
	err := c.cc.Invoke(ctx, TargetGroupsService_GetTargetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetGroupsServiceServer is the server API for TargetGroupsService service.
// All implementations must embed UnimplementedTargetGroupsServiceServer
// for forward compatibility.
type TargetGroupsServiceServer interface {
	ListTargetGroups(context.Context, *ListTargetGroupsRequest) (*ListTargetGroupsResponse, error)
	GetTargetGroup(context.Context, *GetTargetGroupRequest) (*GetTargetGroupResponse, error)
	mustEmbedUnimplementedTargetGroupsServiceServer()
}

// UnimplementedTargetGroupsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetGroupsServiceServer struct{}

func (UnimplementedTargetGroupsServiceServer) ListTargetGroups(context.Context, *ListTargetGroupsRequest) (*ListTargetGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTargetGroups not implemented")
}
func (UnimplementedTargetGroupsServiceServer) GetTargetGroup(context.Context, *GetTargetGroupRequest) (*GetTargetGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTargetGroup not implemented")
}
func (UnimplementedTargetGroupsServiceServer) mustEmbedUnimplementedTargetGroupsServiceServer() {}
func (UnimplementedTargetGroupsServiceServer) testEmbeddedByValue()                             {}

// UnsafeTargetGroupsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetGroupsServiceServer will
// result in compilation errors.
type UnsafeTargetGroupsServiceServer interface {
	mustEmbedUnimplementedTargetGroupsServiceServer()
}

func RegisterTargetGroupsServiceServer(s grpc.ServiceRegistrar, srv TargetGroupsServiceServer) {
	// If the following call panics, it indicates UnimplementedTargetGroupsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetGroupsService_ServiceDesc, srv)
}

func _TargetGroupsService_ListTargetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTargetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetGroupsServiceServer).ListTargetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetGroupsService_ListTargetGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetGroupsServiceServer).ListTargetGroups(ctx, req.(*ListTargetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TargetGroupsService_GetTargetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetGroupsServiceServer).GetTargetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetGroupsService_GetTargetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetGroupsServiceServer).GetTargetGroup(ctx, req.(*GetTargetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetGroupsService_ServiceDesc is the grpc.ServiceDesc for TargetGroupsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetGroupsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metricsherlock.targetgroups.v1.TargetGroupsService",
	HandlerType: (*TargetGroupsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTargetGroups",
			Handler:    _TargetGroupsService_ListTargetGroups_Handler,
		},
		{
			MethodName: "GetTargetGroup",
			Handler:    _TargetGroupsService_GetTargetGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metricsherlock/targetgroups/v1/target_groups.proto",
}
