// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.0
// source: proto/metricsherlock/targetgroups/v1/target_groups.proto

package targetgroupsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTargetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamName      string                 `protobuf:"bytes,1,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetGroupsRequest) Reset() {
	*x = ListTargetGroupsRequest{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetGroupsRequest) ProtoMessage() {}

func (x *ListTargetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTargetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{0}
}

func (x *ListTargetGroupsRequest) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

type ListTargetGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroups  []*TargetGroupSummary  `protobuf:"bytes,1,rep,name=target_groups,json=targetGroups,proto3" json:"target_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetGroupsResponse) Reset() {
	*x = ListTargetGroupsResponse{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetGroupsResponse) ProtoMessage() {}

func (x *ListTargetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTargetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{1}
}

func (x *ListTargetGroupsResponse) GetTargetGroups() []*TargetGroupSummary {
	if x != nil {
		return x.TargetGroups
	}
	return nil
}

type GetTargetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetGroupRequest) Reset() {
	*x = GetTargetGroupRequest{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetGroupRequest) ProtoMessage() {}

func (x *GetTargetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetTargetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{2}
}

func (x *GetTargetGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTargetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetGroup   *TargetGroupDetails    `protobuf:"bytes,1,opt,name=target_group,json=targetGroup,proto3" json:"target_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetGroupResponse) Reset() {
	*x = GetTargetGroupResponse{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetGroupResponse) ProtoMessage() {}

func (x *GetTargetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetTargetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{3}
}

func (x *GetTargetGroupResponse) GetTargetGroup() *TargetGroupDetails {
	if x != nil {
		return x.TargetGroup
	}
	return nil
}

type TargetGroupDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         *TargetGroupSummary    `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Violations      *ViolationDetails      `protobuf:"bytes,2,opt,name=violations,proto3" json:"violations,omitempty"`
	ReportCreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=report_created_at,json=reportCreatedAt,proto3" json:"report_created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TargetGroupDetails) Reset() {
	*x = TargetGroupDetails{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupDetails) ProtoMessage() {}

func (x *TargetGroupDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupDetails.ProtoReflect.Descriptor instead.
func (*TargetGroupDetails) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{4}
}

func (x *TargetGroupDetails) GetSummary() *TargetGroupSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *TargetGroupDetails) GetViolations() *ViolationDetails {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *TargetGroupDetails) GetReportCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportCreatedAt
	}
	return nil
}

type TargetGroupSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Env            string                 `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	Cluster        string                 `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Job            string                 `protobuf:"bytes,5,opt,name=job,proto3" json:"job,omitempty"`
	TeamName       string                 `protobuf:"bytes,6,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	FirstCheck     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=first_check,json=firstCheck,proto3" json:"first_check,omitempty"`
	LastCheck      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	ViolationStats *ViolationStats        `protobuf:"bytes,9,opt,name=violation_stats,json=violationStats,proto3" json:"violation_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetGroupSummary) Reset() {
	*x = TargetGroupSummary{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGroupSummary) ProtoMessage() {}

func (x *TargetGroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGroupSummary.ProtoReflect.Descriptor instead.
func (*TargetGroupSummary) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{5}
}

func (x *TargetGroupSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TargetGroupSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetGroupSummary) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *TargetGroupSummary) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *TargetGroupSummary) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *TargetGroupSummary) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *TargetGroupSummary) GetFirstCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstCheck
	}
	return nil
}

func (x *TargetGroupSummary) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *TargetGroupSummary) GetViolationStats() *ViolationStats {
	if x != nil {
		return x.ViolationStats
	}
	return nil
}

type ViolationStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	MetricNameTooLong int32                  `protobuf:"varint,2,opt,name=metric_name_too_long,json=metricNameTooLong,proto3" json:"metric_name_too_long,omitempty"`
	LabelNameTooLong  int32                  `protobuf:"varint,3,opt,name=label_name_too_long,json=labelNameTooLong,proto3" json:"label_name_too_long,omitempty"`
	LabelValueTooLong int32                  `protobuf:"varint,4,opt,name=label_value_too_long,json=labelValueTooLong,proto3" json:"label_value_too_long,omitempty"`
	Cardinality       int32                  `protobuf:"varint,5,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	HistogramBuckets  int32                  `protobuf:"varint,6,opt,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty"`
	ResponseWeight    int64                  `protobuf:"varint,7,opt,name=response_weight,json=responseWeight,proto3" json:"response_weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ViolationStats) Reset() {
	*x = ViolationStats{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViolationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViolationStats) ProtoMessage() {}

func (x *ViolationStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViolationStats.ProtoReflect.Descriptor instead.
func (*ViolationStats) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{6}
}

func (x *ViolationStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ViolationStats) GetMetricNameTooLong() int32 {
	if x != nil {
		return x.MetricNameTooLong
	}
	return 0
}

func (x *ViolationStats) GetLabelNameTooLong() int32 {
	if x != nil {
		return x.LabelNameTooLong
	}
	return 0
}

func (x *ViolationStats) GetLabelValueTooLong() int32 {
	if x != nil {
		return x.LabelValueTooLong
	}
	return 0
}

func (x *ViolationStats) GetCardinality() int32 {
	if x != nil {
		return x.Cardinality
	}
	return 0
}

func (x *ViolationStats) GetHistogramBuckets() int32 {
	if x != nil {
		return x.HistogramBuckets
	}
	return 0
}

func (x *ViolationStats) GetResponseWeight() int64 {
	if x != nil {
		return x.ResponseWeight
	}
	return 0
}

type ViolationDetails struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	MetricNameTooLong []*MetricNameViolation       `protobuf:"bytes,1,rep,name=metric_name_too_long,json=metricNameTooLong,proto3" json:"metric_name_too_long,omitempty"`
	LabelNameTooLong  []*LabelNameViolation        `protobuf:"bytes,2,rep,name=label_name_too_long,json=labelNameTooLong,proto3" json:"label_name_too_long,omitempty"`
	LabelValueTooLong []*LabelValueViolation       `protobuf:"bytes,3,rep,name=label_value_too_long,json=labelValueTooLong,proto3" json:"label_value_too_long,omitempty"`
	Cardinality       []*CardinalityViolation      `protobuf:"bytes,4,rep,name=cardinality,proto3" json:"cardinality,omitempty"`
	HistogramBuckets  []*HistogramBucketsViolation `protobuf:"bytes,5,rep,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty"`
	Max               *MaxViolationStats           `protobuf:"bytes,6,opt,name=max,proto3" json:"max,omitempty"`
	ResponseWeight    int64                        `protobuf:"varint,7,opt,name=response_weight,json=responseWeight,proto3" json:"response_weight,omitempty"`
	Checks            *CheckMetrics                `protobuf:"bytes,8,opt,name=checks,proto3" json:"checks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ViolationDetails) Reset() {
	*x = ViolationDetails{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViolationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViolationDetails) ProtoMessage() {}

func (x *ViolationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViolationDetails.ProtoReflect.Descriptor instead.
func (*ViolationDetails) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{7}
}

func (x *ViolationDetails) GetMetricNameTooLong() []*MetricNameViolation {
	if x != nil {
		return x.MetricNameTooLong
	}
	return nil
}

func (x *ViolationDetails) GetLabelNameTooLong() []*LabelNameViolation {
	if x != nil {
		return x.LabelNameTooLong
	}
	return nil
}

func (x *ViolationDetails) GetLabelValueTooLong() []*LabelValueViolation {
	if x != nil {
		return x.LabelValueTooLong
	}
	return nil
}

func (x *ViolationDetails) GetCardinality() []*CardinalityViolation {
	if x != nil {
		return x.Cardinality
	}
	return nil
}

func (x *ViolationDetails) GetHistogramBuckets() []*HistogramBucketsViolation {
	if x != nil {
		return x.HistogramBuckets
	}
	return nil
}

func (x *ViolationDetails) GetMax() *MaxViolationStats {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *ViolationDetails) GetResponseWeight() int64 {
	if x != nil {
		return x.ResponseWeight
	}
	return 0
}

func (x *ViolationDetails) GetChecks() *CheckMetrics {
	if x != nil {
		return x.Checks
	}
	return nil
}

type CheckMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MetricNameLength *CheckMetric           `protobuf:"bytes,1,opt,name=metric_name_length,json=metricNameLength,proto3" json:"metric_name_length,omitempty"`
	LabelNameLength  *CheckMetric           `protobuf:"bytes,2,opt,name=label_name_length,json=labelNameLength,proto3" json:"label_name_length,omitempty"`
	LabelValueLength *CheckMetric           `protobuf:"bytes,3,opt,name=label_value_length,json=labelValueLength,proto3" json:"label_value_length,omitempty"`
	Cardinality      *CheckMetric           `protobuf:"bytes,4,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	HistogramBuckets *CheckMetric           `protobuf:"bytes,5,opt,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty"`
	ResponseWeight   *CheckMetric           `protobuf:"bytes,6,opt,name=response_weight,json=responseWeight,proto3" json:"response_weight,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckMetrics) Reset() {
	*x = CheckMetrics{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMetrics) ProtoMessage() {}

func (x *CheckMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMetrics.ProtoReflect.Descriptor instead.
func (*CheckMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{8}
}

func (x *CheckMetrics) GetMetricNameLength() *CheckMetric {
	if x != nil {
		return x.MetricNameLength
	}
	return nil
}

func (x *CheckMetrics) GetLabelNameLength() *CheckMetric {
	if x != nil {
		return x.LabelNameLength
	}
	return nil
}

func (x *CheckMetrics) GetLabelValueLength() *CheckMetric {
	if x != nil {
		return x.LabelValueLength
	}
	return nil
}

func (x *CheckMetrics) GetCardinality() *CheckMetric {
	if x != nil {
		return x.Cardinality
	}
	return nil
}

func (x *CheckMetrics) GetHistogramBuckets() *CheckMetric {
	if x != nil {
		return x.HistogramBuckets
	}
	return nil
}

func (x *CheckMetrics) GetResponseWeight() *CheckMetric {
	if x != nil {
		return x.ResponseWeight
	}
	return nil
}

type CheckMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Current       int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMetric) Reset() {
	*x = CheckMetric{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMetric) ProtoMessage() {}

func (x *CheckMetric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMetric.ProtoReflect.Descriptor instead.
func (*CheckMetric) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{9}
}

func (x *CheckMetric) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckMetric) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

type MaxViolationStats struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	MetricNameTooLong *MetricNameViolation       `protobuf:"bytes,1,opt,name=metric_name_too_long,json=metricNameTooLong,proto3" json:"metric_name_too_long,omitempty"`
	LabelNameTooLong  *LabelNameViolation        `protobuf:"bytes,2,opt,name=label_name_too_long,json=labelNameTooLong,proto3" json:"label_name_too_long,omitempty"`
	LabelValueTooLong *LabelValueViolation       `protobuf:"bytes,3,opt,name=label_value_too_long,json=labelValueTooLong,proto3" json:"label_value_too_long,omitempty"`
	Cardinality       *CardinalityViolation      `protobuf:"bytes,4,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	HistogramBuckets  *HistogramBucketsViolation `protobuf:"bytes,5,opt,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaxViolationStats) Reset() {
	*x = MaxViolationStats{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxViolationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxViolationStats) ProtoMessage() {}

func (x *MaxViolationStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxViolationStats.ProtoReflect.Descriptor instead.
func (*MaxViolationStats) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{10}
}

func (x *MaxViolationStats) GetMetricNameTooLong() *MetricNameViolation {
	if x != nil {
		return x.MetricNameTooLong
	}
	return nil
}

func (x *MaxViolationStats) GetLabelNameTooLong() *LabelNameViolation {
	if x != nil {
		return x.LabelNameTooLong
	}
	return nil
}

func (x *MaxViolationStats) GetLabelValueTooLong() *LabelValueViolation {
	if x != nil {
		return x.LabelValueTooLong
	}
	return nil
}

func (x *MaxViolationStats) GetCardinality() *CardinalityViolation {
	if x != nil {
		return x.Cardinality
	}
	return nil
}

func (x *MaxViolationStats) GetHistogramBuckets() *HistogramBucketsViolation {
	if x != nil {
		return x.HistogramBuckets
	}
	return nil
}

type MetricNameViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricNameViolation) Reset() {
	*x = MetricNameViolation{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricNameViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricNameViolation) ProtoMessage() {}

func (x *MetricNameViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricNameViolation.ProtoReflect.Descriptor instead.
func (*MetricNameViolation) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{11}
}

func (x *MetricNameViolation) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricNameViolation) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LabelNameViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	LabelName     string                 `protobuf:"bytes,2,opt,name=label_name,json=labelName,proto3" json:"label_name,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelNameViolation) Reset() {
	*x = LabelNameViolation{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelNameViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelNameViolation) ProtoMessage() {}

func (x *LabelNameViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelNameViolation.ProtoReflect.Descriptor instead.
func (*LabelNameViolation) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{12}
}

func (x *LabelNameViolation) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *LabelNameViolation) GetLabelName() string {
	if x != nil {
		return x.LabelName
	}
	return ""
}

func (x *LabelNameViolation) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LabelValueViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	LabelName     string                 `protobuf:"bytes,2,opt,name=label_name,json=labelName,proto3" json:"label_name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Length        int32                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelValueViolation) Reset() {
	*x = LabelValueViolation{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelValueViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelValueViolation) ProtoMessage() {}

func (x *LabelValueViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelValueViolation.ProtoReflect.Descriptor instead.
func (*LabelValueViolation) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{13}
}

func (x *LabelValueViolation) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *LabelValueViolation) GetLabelName() string {
	if x != nil {
		return x.LabelName
	}
	return ""
}

func (x *LabelValueViolation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LabelValueViolation) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type CardinalityViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardinalityViolation) Reset() {
	*x = CardinalityViolation{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardinalityViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardinalityViolation) ProtoMessage() {}

func (x *CardinalityViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardinalityViolation.ProtoReflect.Descriptor instead.
func (*CardinalityViolation) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{14}
}

func (x *CardinalityViolation) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *CardinalityViolation) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HistogramBucketsViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Buckets       int32                  `protobuf:"varint,2,opt,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucketsViolation) Reset() {
	*x = HistogramBucketsViolation{}
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucketsViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucketsViolation) ProtoMessage() {}

func (x *HistogramBucketsViolation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucketsViolation.ProtoReflect.Descriptor instead.
func (*HistogramBucketsViolation) Descriptor() ([]byte, []int) {
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP(), []int{15}
}

func (x *HistogramBucketsViolation) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *HistogramBucketsViolation) GetBuckets() int32 {
	if x != nil {
		return x.Buckets
	}
	return 0
}

var File_proto_metricsherlock_targetgroups_v1_target_groups_proto protoreflect.FileDescriptor

const file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDesc = "" +
	"\n" +
	"8proto/metricsherlock/targetgroups/v1/target_groups.proto\x12\x1emetricsherlock.targetgroups.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x17ListTargetGroupsRequest\x12\x1b\n" +
	"\tteam_name\x18\x01 \x01(\tR\bteamName\"s\n" +
	"\x18ListTargetGroupsResponse\x12W\n" +
	"\rtarget_groups\x18\x01 \x03(\v22.metricsherlock.targetgroups.v1.TargetGroupSummaryR\ftargetGroups\"'\n" +
	"\x15GetTargetGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"o\n" +
	"\x16GetTargetGroupResponse\x12U\n" +
	"\ftarget_group\x18\x01 \x01(\v22.metricsherlock.targetgroups.v1.TargetGroupDetailsR\vtargetGroup\"\xfc\x01\n" +
	"\x12TargetGroupDetails\x12L\n" +
	"\asummary\x18\x01 \x01(\v22.metricsherlock.targetgroups.v1.TargetGroupSummaryR\asummary\x12P\n" +
	"\n" +
	"violations\x18\x02 \x01(\v20.metricsherlock.targetgroups.v1.ViolationDetailsR\n" +
	"violations\x12F\n" +
	"\x11report_created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0freportCreatedAt\"\xe4\x02\n" +
	"\x12TargetGroupSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03env\x18\x03 \x01(\tR\x03env\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12\x10\n" +
	"\x03job\x18\x05 \x01(\tR\x03job\x12\x1b\n" +
	"\tteam_name\x18\x06 \x01(\tR\bteamName\x12;\n" +
	"\vfirst_check\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"firstCheck\x129\n" +
	"\n" +
	"last_check\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12W\n" +
	"\x0fviolation_stats\x18\t \x01(\v2..metricsherlock.targetgroups.v1.ViolationStatsR\x0eviolationStats\"\xaf\x02\n" +
	"\x0eViolationStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12/\n" +
	"\x14metric_name_too_long\x18\x02 \x01(\x05R\x11metricNameTooLong\x12-\n" +
	"\x13label_name_too_long\x18\x03 \x01(\x05R\x10labelNameTooLong\x12/\n" +
	"\x14label_value_too_long\x18\x04 \x01(\x05R\x11labelValueTooLong\x12 \n" +
	"\vcardinality\x18\x05 \x01(\x05R\vcardinality\x12+\n" +
	"\x11histogram_buckets\x18\x06 \x01(\x05R\x10histogramBuckets\x12'\n" +
	"\x0fresponse_weight\x18\a \x01(\x03R\x0eresponseWeight\"\xb5\x05\n" +
	"\x10ViolationDetails\x12d\n" +
	"\x14metric_name_too_long\x18\x01 \x03(\v23.metricsherlock.targetgroups.v1.MetricNameViolationR\x11metricNameTooLong\x12a\n" +
	"\x13label_name_too_long\x18\x02 \x03(\v22.metricsherlock.targetgroups.v1.LabelNameViolationR\x10labelNameTooLong\x12d\n" +
	"\x14label_value_too_long\x18\x03 \x03(\v23.metricsherlock.targetgroups.v1.LabelValueViolationR\x11labelValueTooLong\x12V\n" +
	"\vcardinality\x18\x04 \x03(\v24.metricsherlock.targetgroups.v1.CardinalityViolationR\vcardinality\x12f\n" +
	"\x11histogram_buckets\x18\x05 \x03(\v29.metricsherlock.targetgroups.v1.HistogramBucketsViolationR\x10histogramBuckets\x12C\n" +
	"\x03max\x18\x06 \x01(\v21.metricsherlock.targetgroups.v1.MaxViolationStatsR\x03max\x12'\n" +
	"\x0fresponse_weight\x18\a \x01(\x03R\x0eresponseWeight\x12D\n" +
	"\x06checks\x18\b \x01(\v2,.metricsherlock.targetgroups.v1.CheckMetricsR\x06checks\"\x9c\x04\n" +
	"\fCheckMetrics\x12Y\n" +
	"\x12metric_name_length\x18\x01 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\x10metricNameLength\x12W\n" +
	"\x11label_name_length\x18\x02 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\x0flabelNameLength\x12Y\n" +
	"\x12label_value_length\x18\x03 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\x10labelValueLength\x12M\n" +
	"\vcardinality\x18\x04 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\vcardinality\x12X\n" +
	"\x11histogram_buckets\x18\x05 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\x10histogramBuckets\x12T\n" +
	"\x0fresponse_weight\x18\x06 \x01(\v2+.metricsherlock.targetgroups.v1.CheckMetricR\x0eresponseWeight\"=\n" +
	"\vCheckMetric\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\"\x82\x04\n" +
	"\x11MaxViolationStats\x12d\n" +
	"\x14metric_name_too_long\x18\x01 \x01(\v23.metricsherlock.targetgroups.v1.MetricNameViolationR\x11metricNameTooLong\x12a\n" +
	"\x13label_name_too_long\x18\x02 \x01(\v22.metricsherlock.targetgroups.v1.LabelNameViolationR\x10labelNameTooLong\x12d\n" +
	"\x14label_value_too_long\x18\x03 \x01(\v23.metricsherlock.targetgroups.v1.LabelValueViolationR\x11labelValueTooLong\x12V\n" +
	"\vcardinality\x18\x04 \x01(\v24.metricsherlock.targetgroups.v1.CardinalityViolationR\vcardinality\x12f\n" +
	"\x11histogram_buckets\x18\x05 \x01(\v29.metricsherlock.targetgroups.v1.HistogramBucketsViolationR\x10histogramBuckets\"N\n" +
	"\x13MetricNameViolation\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"l\n" +
	"\x12LabelNameViolation\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1d\n" +
	"\n" +
	"label_name\x18\x02 \x01(\tR\tlabelName\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\"\x83\x01\n" +
	"\x13LabelValueViolation\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x1d\n" +
	"\n" +
	"label_name\x18\x02 \x01(\tR\tlabelName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x05R\x06length\"M\n" +
	"\x14CardinalityViolation\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"V\n" +
	"\x19HistogramBucketsViolation\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x18\n" +
	"\abuckets\x18\x02 \x01(\x05R\abuckets2\xe2\x02\n" +
	"\x13TargetGroupsService\x12\xa4\x01\n" +
	"\x10ListTargetGroups\x127.metricsherlock.targetgroups.v1.ListTargetGroupsRequest\x1a8.metricsherlock.targetgroups.v1.ListTargetGroupsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/target-groups\x12\xa3\x01\n" +
	"\x0eGetTargetGroup\x125.metricsherlock.targetgroups.v1.GetTargetGroupRequest\x1a6.metricsherlock.targetgroups.v1.GetTargetGroupResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/target-groups/{id}BcZagit.server.lan/maksim/metric-sherlock-diploma/proto/metricsherlock/targetgroups/v1;targetgroupsv1b\x06proto3"

var (
	file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescOnce sync.Once
	file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescData []byte
)

func file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescGZIP() []byte {
	file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescOnce.Do(func() {
		file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDesc), len(file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDesc)))
	})
	return file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDescData
}

var file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_metricsherlock_targetgroups_v1_target_groups_proto_goTypes = []any{
	(*ListTargetGroupsRequest)(nil),   // 0: metricsherlock.targetgroups.v1.ListTargetGroupsRequest
	(*ListTargetGroupsResponse)(nil),  // 1: metricsherlock.targetgroups.v1.ListTargetGroupsResponse
	(*GetTargetGroupRequest)(nil),     // 2: metricsherlock.targetgroups.v1.GetTargetGroupRequest
	(*GetTargetGroupResponse)(nil),    // 3: metricsherlock.targetgroups.v1.GetTargetGroupResponse
	(*TargetGroupDetails)(nil),        // 4: metricsherlock.targetgroups.v1.TargetGroupDetails
	(*TargetGroupSummary)(nil),        // 5: metricsherlock.targetgroups.v1.TargetGroupSummary
	(*ViolationStats)(nil),            // 6: metricsherlock.targetgroups.v1.ViolationStats
	(*ViolationDetails)(nil),          // 7: metricsherlock.targetgroups.v1.ViolationDetails
	(*CheckMetrics)(nil),              // 8: metricsherlock.targetgroups.v1.CheckMetrics
	(*CheckMetric)(nil),               // 9: metricsherlock.targetgroups.v1.CheckMetric
	(*MaxViolationStats)(nil),         // 10: metricsherlock.targetgroups.v1.MaxViolationStats
	(*MetricNameViolation)(nil),       // 11: metricsherlock.targetgroups.v1.MetricNameViolation
	(*LabelNameViolation)(nil),        // 12: metricsherlock.targetgroups.v1.LabelNameViolation
	(*LabelValueViolation)(nil),       // 13: metricsherlock.targetgroups.v1.LabelValueViolation
	(*CardinalityViolation)(nil),      // 14: metricsherlock.targetgroups.v1.CardinalityViolation
	(*HistogramBucketsViolation)(nil), // 15: metricsherlock.targetgroups.v1.HistogramBucketsViolation
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
}
var file_proto_metricsherlock_targetgroups_v1_target_groups_proto_depIdxs = []int32{
	5,  // 0: metricsherlock.targetgroups.v1.ListTargetGroupsResponse.target_groups:type_name -> metricsherlock.targetgroups.v1.TargetGroupSummary
	4,  // 1: metricsherlock.targetgroups.v1.GetTargetGroupResponse.target_group:type_name -> metricsherlock.targetgroups.v1.TargetGroupDetails
	5,  // 2: metricsherlock.targetgroups.v1.TargetGroupDetails.summary:type_name -> metricsherlock.targetgroups.v1.TargetGroupSummary
	7,  // 3: metricsherlock.targetgroups.v1.TargetGroupDetails.violations:type_name -> metricsherlock.targetgroups.v1.ViolationDetails
	16, // 4: metricsherlock.targetgroups.v1.TargetGroupDetails.report_created_at:type_name -> google.protobuf.Timestamp
	16, // 5: metricsherlock.targetgroups.v1.TargetGroupSummary.first_check:type_name -> google.protobuf.Timestamp
	16, // 6: metricsherlock.targetgroups.v1.TargetGroupSummary.last_check:type_name -> google.protobuf.Timestamp
	6,  // 7: metricsherlock.targetgroups.v1.TargetGroupSummary.violation_stats:type_name -> metricsherlock.targetgroups.v1.ViolationStats
	11, // 8: metricsherlock.targetgroups.v1.ViolationDetails.metric_name_too_long:type_name -> metricsherlock.targetgroups.v1.MetricNameViolation
	12, // 9: metricsherlock.targetgroups.v1.ViolationDetails.label_name_too_long:type_name -> metricsherlock.targetgroups.v1.LabelNameViolation
	13, // 10: metricsherlock.targetgroups.v1.ViolationDetails.label_value_too_long:type_name -> metricsherlock.targetgroups.v1.LabelValueViolation
	14, // 11: metricsherlock.targetgroups.v1.ViolationDetails.cardinality:type_name -> metricsherlock.targetgroups.v1.CardinalityViolation
	15, // 12: metricsherlock.targetgroups.v1.ViolationDetails.histogram_buckets:type_name -> metricsherlock.targetgroups.v1.HistogramBucketsViolation
	10, // 13: metricsherlock.targetgroups.v1.ViolationDetails.max:type_name -> metricsherlock.targetgroups.v1.MaxViolationStats
	8,  // 14: metricsherlock.targetgroups.v1.ViolationDetails.checks:type_name -> metricsherlock.targetgroups.v1.CheckMetrics
	9,  // 15: metricsherlock.targetgroups.v1.CheckMetrics.metric_name_length:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	9,  // 16: metricsherlock.targetgroups.v1.CheckMetrics.label_name_length:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	9,  // 17: metricsherlock.targetgroups.v1.CheckMetrics.label_value_length:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	9,  // 18: metricsherlock.targetgroups.v1.CheckMetrics.cardinality:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	9,  // 19: metricsherlock.targetgroups.v1.CheckMetrics.histogram_buckets:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	9,  // 20: metricsherlock.targetgroups.v1.CheckMetrics.response_weight:type_name -> metricsherlock.targetgroups.v1.CheckMetric
	11, // 21: metricsherlock.targetgroups.v1.MaxViolationStats.metric_name_too_long:type_name -> metricsherlock.targetgroups.v1.MetricNameViolation
	12, // 22: metricsherlock.targetgroups.v1.MaxViolationStats.label_name_too_long:type_name -> metricsherlock.targetgroups.v1.LabelNameViolation
	13, // 23: metricsherlock.targetgroups.v1.MaxViolationStats.label_value_too_long:type_name -> metricsherlock.targetgroups.v1.LabelValueViolation
	14, // 24: metricsherlock.targetgroups.v1.MaxViolationStats.cardinality:type_name -> metricsherlock.targetgroups.v1.CardinalityViolation
	15, // 25: metricsherlock.targetgroups.v1.MaxViolationStats.histogram_buckets:type_name -> metricsherlock.targetgroups.v1.HistogramBucketsViolation
	0,  // 26: metricsherlock.targetgroups.v1.TargetGroupsService.ListTargetGroups:input_type -> metricsherlock.targetgroups.v1.ListTargetGroupsRequest
	2,  // 27: metricsherlock.targetgroups.v1.TargetGroupsService.GetTargetGroup:input_type -> metricsherlock.targetgroups.v1.GetTargetGroupRequest
	1,  // 28: metricsherlock.targetgroups.v1.TargetGroupsService.ListTargetGroups:output_type -> metricsherlock.targetgroups.v1.ListTargetGroupsResponse
	3,  // 29: metricsherlock.targetgroups.v1.TargetGroupsService.GetTargetGroup:output_type -> metricsherlock.targetgroups.v1.GetTargetGroupResponse
	28, // [28:30] is the sub-list for method output_type
	26, // [26:28] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_metricsherlock_targetgroups_v1_target_groups_proto_init() }
func file_proto_metricsherlock_targetgroups_v1_target_groups_proto_init() {
	if File_proto_metricsherlock_targetgroups_v1_target_groups_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDesc), len(file_proto_metricsherlock_targetgroups_v1_target_groups_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metricsherlock_targetgroups_v1_target_groups_proto_goTypes,
		DependencyIndexes: file_proto_metricsherlock_targetgroups_v1_target_groups_proto_depIdxs,
		MessageInfos:      file_proto_metricsherlock_targetgroups_v1_target_groups_proto_msgTypes,
	}.Build()
	File_proto_metricsherlock_targetgroups_v1_target_groups_proto = out.File
	file_proto_metricsherlock_targetgroups_v1_target_groups_proto_goTypes = nil
	file_proto_metricsherlock_targetgroups_v1_target_groups_proto_depIdxs = nil
}
